// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi14RAnRU2tRl-o1JuDxThRtmaLeARXSI',
    appId: '1:173072342259:web:86b6d5f4a7fc9c7ed1ab86',
    messagingSenderId: '173072342259',
    projectId: 'suroy-68a91',
    authDomain: 'suroy-68a91.firebaseapp.com',
    storageBucket: 'suroy-68a91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbejhseYo3don9udIJwK8s__N90FZdbNc',
    appId: '1:173072342259:android:5e0441b97a22c021d1ab86',
    messagingSenderId: '173072342259',
    projectId: 'suroy-68a91',
    storageBucket: 'suroy-68a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwkp_isAV_-fR9Kv7y7ne6CNeYi2rycs',
    appId: '1:173072342259:ios:e53256609dc9d02bd1ab86',
    messagingSenderId: '173072342259',
    projectId: 'suroy-68a91',
    storageBucket: 'suroy-68a91.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwkp_isAV_-fR9Kv7y7ne6CNeYi2rycs',
    appId: '1:173072342259:ios:e53256609dc9d02bd1ab86',
    messagingSenderId: '173072342259',
    projectId: 'suroy-68a91',
    storageBucket: 'suroy-68a91.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi14RAnRU2tRl-o1JuDxThRtmaLeARXSI',
    appId: '1:173072342259:web:2ec470054d78ea21d1ab86',
    messagingSenderId: '173072342259',
    projectId: 'suroy-68a91',
    authDomain: 'suroy-68a91.firebaseapp.com',
    storageBucket: 'suroy-68a91.firebasestorage.app',
  );
}
